### ISSUE TITLE
serial port datat transfare 

### ISSUE THREAD

**Issue by Armini-inv** [lucky01/OpenDyno#1]
hi, 
thx for your project its a great job. i have designed my own hardware with ATmega32 and i send data to PC with usb-to-ttl module (the same as serial port) ,i want to test your software, in what format should i send the data to PC that your software can read them? thx

**Comment by lucky01** [comment]
You find all information in the source of the firmware I used to collect and send the data to the PC is here
https://github.com/lucky01/OpenDyno/blob/master/firmware/V100.bas#L143
